#!/bin/bash

kubeadm reset -f

iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

sysctl net.bridge.bridge-nf-call-iptables=1

rm -rf /etc/cni/net.d

ip link del cni0

ip link del flannel.1

rm -rf $HOME/.kube

rm /etc/systemd/system/kubelet.service.d/*
