apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.2
localAPIEndpoint:
  advertiseAddress: 10.0.2.7        # 此处改为本机IP
  bindPort: 6443
imageRepository: "registry.aliyuncs.com/google_containers"
controlPlaneEndpoint: "kubeapiserver.tcy365.org:6443"
etcd:
    external:
        endpoints:
        - https://10.0.2.4:2379
        - https://10.0.2.5:2379
        - https://10.0.2.6:2379
        caFile: /etc/kubernetes/ssl/etcd-ca.pem
        certFile: /etc/kubernetes/ssl/etcd-client.pem
        keyFile: /etc/kubernetes/ssl/etcd-client-key.pem		
kubernetesVersion: v1.19.2
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/16
  podSubnet: 10.244.0.0/16    # pod子网，和Flannel中要一致
