apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server1
spec:
  serviceName: consul-server1
  replicas: 1
  selector:
    matchLabels:
      app: consul-server
      instance: consul-server1
  template: 
    metadata:
      labels:
        app: consul-server
        instance: consul-server1
    spec:      
      terminationGracePeriodSeconds: 10
      containers:
      - name: consul-server
        image: consul:latest
        args:
          - "agent"
          - "-server"
          - "-datacenter=dc1"
          - "-bootstrap-expect=1"
          - "-ui"
          - "-data-dir=/consul/data"
          - "-node=$(PODIP)"
          - "-bind=0.0.0.0"
          - "-client=0.0.0.0"
        env:
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOSTIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 8443
            name: https-port
          - containerPort: 8080
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server
