apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:   # route用来设置报警的分发策略
      group_by: ['alertname']  # 采用哪个标签来作为分组依据
      group_wait: 10s   # 组告警等待时间。也就是告警产生后等待10s，如果有同组告警一起发出
      group_interval: 10s  # 两组告警的间隔时间
      repeat_interval: 20m  # 重复告警的间隔时间，减少相同邮件的发送频率
      receiver: 'default-receiver'  # 设置默认接收人
      routes:   # 可以指定哪些组接手哪些消息
      - match_re:
          group: '^netcore.*'
        group_wait: 10s
        continue: true
        receiver: 'netcore-receiver'
    receivers:
    - name: 'default-receiver'
      webhook_configs:
      - url: 'http://192.168.10.105:5000/api/alert/hook'
        send_resolved: true
    - name: 'netcore-receiver'
      webhook_configs:
      - url: 'http://192.168.10.105:5000/api/alert/k8snetcorehook'
        send_resolved: true
