apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: alertmanager-deployment
  name: alertmanager
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - image: prom/alertmanager:v0.21.0
        name: alertmanager 
        command:
        - "/bin/alertmanager"
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--cluster.listen-address="
        ports:
        - containerPort: 9093
          protocol: TCP
          hostPort: 9093
        volumeMounts:
        - mountPath: "/etc/alertmanager"
          name: config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
