apiVersion: v1
kind: Service
metadata:  
   name: consul-ui
   labels:    
     name: consul-ui
spec:  
   type: NodePort  
   ports:    
    - name: http      
      port: 8500      
      targetPort: 8500
      nodePort: 32000    
   selector:    
    app: consul-server
